### ISSUE TITLE
Restrictions to subpaths

### ISSUE THREAD

**Issue by bsrajesh** [fbaligand/lognavigator#2]
how do i restrict the subpath?
http://localhost:8045/lognavigator-1.6.1/logs/tomcat-log/list?subPath=..

.. (2 dots) will navigate to other folders and view files. this allowed others to view password in tomcat-users. how to i control this navigation and restrict only to the directories paths.

**Comment by fbaligand** [comment]
Currently, lognavigator has no such feature.
But I agree that would be a nice-to-have feature to be able to block users to see elsewhere than configured directories.

I can add an advanced option named `block-external-paths` (boolean), so that when it's enabled, users can't list other paths.
What you think ?
By the way, if you have a better name for this option, tell me :)

**Comment by bsrajesh** [comment]
this will be fine. i will wait for this options and test

**Comment by fbaligand** [comment]
Hi @bsrajesh 
I just released [lognavigator 1.6.2](https://github.com/fbaligand/lognavigator/releases/tag/lognavigator-1.6.2) 
You can download it and test id.

You can activate the new option, using 2 ways  :
- define JNDI environment variable : `filelist.blockexternalpaths=true`
- define java system property : `filelist.blockexternalpaths=true`

**Comment by bsrajesh** [comment]
Hi fbaligand - This worked like charm. 

We use this mainly on the QA environment and now i will deploy it on staging. 
Saves lot of time as a devops.

Thanks for the help.

**Comment by fbaligand** [comment]
Nice news to hear !
It's appreciable to see that lognavigator is useful !
